services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  backend:
    image: crparichaya/todo-backend:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
      - PORT=15000
    ports:
      - "15000:15000"
    depends_on:
      - mongo

  frontend:
    image: crparichaya/todo-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
